### ISSUE TITLE
required version of python

### ISSUE THREAD

**Issue by KamilSJaron** [Illumina/paragraph#24]
Hello folks, 

I think your required version of python is too old. In the README you write
     
```
Python 3.4+ is required.
```

but on [many places](https://github.com/Illumina/paragraph/blob/master/src/python/lib/grm/vcfgraph/vcfgraph.py#L178) you use [fstrings](https://realpython.com/python-f-strings/), which are a feature of python 3.6+.

We (with @ptranvan) tired to remove all the `fstrings` and run it on `python 3.5`, but we got a super-crazy-long error on the test example you provide. Selected lines of the error log:

```
2019-06-06 16:15:56,155 ERROR    Exception when running vcf2paragraph on /tmp/tmppbauhqg4.vcf.gz
2019-06-06 16:15:56,156 ERROR    Exception when running vcf2paragraph on /tmp/tmpk58pllu3.vcf.gz
2019-06-06 16:15:56,191 ERROR    Traceback (most recent call last):
2
...
2019-06-06 16:15:56,264 ERROR    VCF to JSON conversion failed.
...
Traceback (most recent call last):
  File "bin/multigrmpy.py", line 353, in <module>
    main()
  File "bin/multigrmpy.py", line 349, in main
    run(args)
  File "bin/multigrmpy.py", line 261, in run
    graph_files = load_graph_description(args)
  File "bin/multigrmpy.py", line 52, in load_graph_description
    header, records, event_list = convert_vcf_to_json(args, alt_paths=True)
  File "/stn4/ptranvan/Software/paragraph/paragraph-tools-build/lib/python3/grm/vcf2paragraph/__init__.py", line 156, in convert_vcf_to_json
    variants = pool.map(run_vcf2paragraph, zip(to_process, itertools.repeat(params))) 
  File "/software/lib64/python3.5/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/software/lib64/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
AssertionError: ref-{refSpan}
```

I tried to copy the relevant lines. Also, it could be that we broke something when we were removing that bloody fstrings. Regardless of which case it is, I suppose you should either remove fstrings and test `paragraph` on python 3.4, or update readme to a newer version of python.

Cheers :-)

**Comment by traxexx** [comment]
Sorry about that. Looks like I didn't remove all fstrings. For 2.2 please use py3.6. I'll update this and do a better test in the upcoming v2.3 (mid July).

**Comment by KamilSJaron** [comment]
No worries, who could have anticipated that our cluster python will be so old?! Contrary, thanks for making this software ^^

If we will run into more obstacles in our genotyping journey, we will let you know.

**Comment by traxexx** [comment]
Yes please let me know!

**Comment by KamilSJaron** [comment]
tiny detail (not worth a new issue): 

Line in readme:
```
 - ID: Each sample must have a unique ID. The output VCF will include genotypes for all samples in the manifest
```

should be

```
 - id: Each sample must have a unique ID. The output VCF will include genotypes for all samples in the manifest
```

**Comment by traxexx** [comment]
Thanks for pointing this out! the column name is recognized as lowercase "id" in the manifest. To avoid confusion, we'll update this in next release.

README updated to py3.6 for requirement. Close the issue for now.
