### ISSUE TITLE
Error processing an INV 

### ISSUE THREAD

**Issue by jjfarrell** [Illumina/paragraph#43]
This error below occurs when processing this INV called by MANTA.  Any suggestions?  The variant record is supplying a REF. ALT, SVLEN  and an SVINSEQ.  

`chr6    2893187 MantaINV:4:20498:20498:4:0:0;MantaINV:61660:0:0:1:0:0   C       <INV>   548     PASS    END=2893191;SVTYPE=INV;SVLEN=4;CIPOS=0,4;CIEND=-4,0;HOMLEN=4;HOMSEQ=TATA;SVINSLEN=51;SVINSSEQ=ACGTATATATATACGTATATATAATATATATATTATATATACGTATATATA;INV5;AC=2;AN=9578;FIBC_P=-0.000417444;HWE_SLP_P=-0.195618;FIBC_I=-0.000417444;HWE_SLP_I=-0.195618;MAX_IF=0.749985;MIN_IF=0.749985;LLK0=-281075;BETA_IF=0.49997,-3.8073e-06,1.89345e-06,3.9655e-06,2.17351e-06;ANN=<INV>|intron_variant|MODIFIER|SERPINB9|ENSG00000170542|transcript|ENST00000380698.4|protein_coding|5/6|c.567+220_567+223inv||||||;NS=4789;AF=0.000208812;MAF=0.000208812;AC_Het=2;AC_Hom=0;AC_Hemi=0;HWE=1;ExcHet=0.999896`

It would be nice to get the chromosome in the below error message when running when trouble shooting. 

```
2020-03-09 10:26:55,417 ERROR    Exception when running vcf2paragraph on /scratch/tmppmn0a0d6.vcf.gz
2020-03-09 10:26:55,421 ERROR    Traceback (most recent call last):
2020-03-09 10:26:55,422 ERROR      File "/share/pkg.7/paragraph/2.4a/install/lib/python3/grm/vcf2paragraph/__init__.py", line 286, in run_vcf2paragraph    alt_paths=params["alt_paths"])
2020-03-09 10:26:55,422 ERROR      File "/share/pkg.7/paragraph/2.4a/install/lib/python3/grm/vcf2paragraph/__init__.py", line 86, in convert_vcf    ref, indexed_vcf.name, ins_info_key, chrom, start, end, ref_node_padding, allele_graph)
2020-03-09 10:26:55,422 ERROR      File "/share/pkg.7/paragraph/2.4a/install/lib/python3/grm/vcfgraph/vcfgraph.py", line 128, in create_from_vcf    graph.add_record(record, allele_graph, varId, ins_info_key)
2020-03-09 10:26:55,422 ERROR      File "/share/pkg.7/paragraph/2.4a/install/lib/python3/grm/vcfgraph/vcfgraph.py", line 202, in add_record    self.add_alt(vcf.pos, vcf.stop, ref_sequence, alt_sequence, alt_samples, refSamples)
2020-03-09 10:26:55,423 ERROR      File "/share/pkg.7/paragraph/2.4a/install/lib/python3/grm/vcfgraph/vcfgraph.py", line 296, in add_alt    raise Exception("{}:{} missing REF or ALT sequence.".format(start, end))
2020-03-09 10:26:55,423 ERROR    Exception: 2893187:2893191 missing REF or ALT sequence.
2020-03-09 10:26:55,506 ERROR    VCF to JSON conversion failed.
2020-03-09 10:26:55,509 ERROR    multiprocessing.pool.RemoteTraceback: """Traceback (most recent call last):  File "/share/pkg.7/python3/3.6.9/install/lib/python3.6/multiprocessing/pool.py", line 119, in worker    result = (True, func(*args, **kwds))  File "/share/pkg.7/python3/3.6.9/install/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar    return list(map(*args))  File "/share/pkg.7/paragraph/2.4a/install/lib/python3/grm/vcf2paragraph/__init__.py", line 286, in run_vcf2paragraph    alt_paths=params["alt_paths"])  File "/share/pkg.7/paragraph/2.4a/install/lib/python3/grm/vcf2paragraph/__init__.py", line 86, in convert_vcf    ref, indexed_vcf.name, ins_info_key, chrom, start, end, ref_node_padding, allele_graph)  File "/share/pkg.7/paragraph/2.4a/install/lib/python3/grm/vcfgraph/vcfgraph.py", line 128, in create_from_vcf    graph.add_record(record, allele_graph, varId, ins_info_key)  File "/share/pkg.7/paragraph/2.4a/install/lib/python3/grm/vcfgraph/vcfgraph.py", line 202, in add_record    self.add_alt(vcf.pos, vcf.stop, ref_sequence, alt_sequence, alt_samples, refSamples)  File "/share/pkg.7/paragraph/2.4a/install/lib/python3/grm/vcfgraph/vcfgraph.py", line 296, in add_alt    raise Exception("{}:{} missing REF or ALT sequence.".format(start, end))Exception: 2893187:2893191 missing REF or ALT sequence."""
2020-03-09 10:26:55,509 ERROR    The above exception was the direct cause of the following exception:
2020-03-09 10:26:55,510 ERROR    Traceback (most recent call last):
2020-03-09 10:26:55,510 ERROR      File "/share/pkg.7/paragraph/2.4a/install/bin/multigrmpy.py", line 52, in load_graph_description    header, records, event_list = convert_vcf_to_json(args, alt_paths=True)
2020-03-09 10:26:55,510 ERROR      File "/share/pkg.7/paragraph/2.4a/install/lib/python3/grm/vcf2paragraph/__init__.py", line 156, in convert_vcf_to_json    variants = pool.map(run_vcf2paragraph, zip(to_process, itertools.repeat(params)))
2020-03-09 10:26:55,510 ERROR      File "/share/pkg.7/python3/3.6.9/install/lib/python3.6/multiprocessing/pool.py", line 266, in map    return self._map_async(func, iterable, mapstar, chunksize).get()
2020-03-09 10:26:55,510 ERROR      File "/share/pkg.7/python3/3.6.9/install/lib/python3.6/multiprocessing/pool.py", line 644, in get    raise self._value
2020-03-09 10:26:55,511 ERROR    Exception: 2893187:2893191 missing REF or ALT sequence.
2020-03-09 10:26:55,511 ERROR    multiprocessing.pool.RemoteTraceback: """Traceback (most recent call last):  File "/share/pkg.7/python3/3.6.9/install/lib/python3.6/multiprocessing/pool.py", line 119, in worker    result = (True, func(*args, **kwds))  File "/share/pkg.7/python3/3.6.9/install/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar    return list(map(*args))  File "/share/pkg.7/paragraph/2.4a/install/lib/python3/grm/vcf2paragraph/__init__.py", line 286, in run_vcf2paragraph    alt_paths=params["alt_paths"])  File "/share/pkg.7/paragraph/2.4a/install/lib/python3/grm/vcf2paragraph/__init__.py", line 86, in convert_vcf    ref, indexed_vcf.name, ins_info_key, chrom, start, end, ref_node_padding, allele_graph)  File "/share/pkg.7/paragraph/2.4a/install/lib/python3/grm/vcfgraph/vcfgraph.py", line 128, in create_from_vcf    graph.add_record(record, allele_graph, varId, ins_info_key)  File "/share/pkg.7/paragraph/2.4a/install/lib/python3/grm/vcfgraph/vcfgraph.py", line 202, in add_record    self.add_alt(vcf.pos, vcf.stop, ref_sequence, alt_sequence, alt_samples, refSamples)  File "/share/pkg.7/paragraph/2.4a/install/lib/python3/grm/vcfgraph/vcfgraph.py", line 296, in add_alt    raise Exception("{}:{} missing REF or ALT sequence.".format(start, end))Exception: 2893187:2893191 missing REF or ALT sequence."""
2020-03-09 10:26:55,511 ERROR    The above exception was the direct cause of the following exception:
2020-03-09 10:26:55,511 ERROR    Traceback (most recent call last):
2020-03-09 10:26:55,512 ERROR      File "/share/pkg.7/paragraph/2.4a/install/bin/multigrmpy.py", line 261, in run    graph_files = load_graph_description(args)
2020-03-09 10:26:55,512 ERROR      File "/share/pkg.7/paragraph/2.4a/install/bin/multigrmpy.py", line 52, in load_graph_description    header, records, event_list = convert_vcf_to_json(args, alt_paths=True)
2020-03-09 10:26:55,512 ERROR      File "/share/pkg.7/paragraph/2.4a/install/lib/python3/grm/vcf2paragraph/__init__.py", line 156, in convert_vcf_to_json    variants = pool.map(run_vcf2paragraph, zip(to_process, itertools.repeat(params)))
2020-03-09 10:26:55,512 ERROR      File "/share/pkg.7/python3/3.6.9/install/lib/python3.6/multiprocessing/pool.py", line 266, in map    return self._map_async(func, iterable, mapstar, chunksize).get()
2020-03-09 10:26:55,512 ERROR      File "/share/pkg.7/python3/3.6.9/install/lib/python3.6/multiprocessing/pool.py", line 644, in get    raise self._value
2020-03-09 10:26:55,513 ERROR    Exception: 2893187:2893191 missing REF or ALT sequence.
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/share/pkg.7/python3/3.6.9/install/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/share/pkg.7/python3/3.6.9/install/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/share/pkg.7/paragraph/2.4a/install/lib/python3/grm/vcf2paragraph/__init__.py", line 286, in run_vcf2paragraph
    alt_paths=params["alt_paths"])
  File "/share/pkg.7/paragraph/2.4a/install/lib/python3/grm/vcf2paragraph/__init__.py", line 86, in convert_vcf
    ref, indexed_vcf.name, ins_info_key, chrom, start, end, ref_node_padding, allele_graph)
  File "/share/pkg.7/paragraph/2.4a/install/lib/python3/grm/vcfgraph/vcfgraph.py", line 128, in create_from_vcf
    graph.add_record(record, allele_graph, varId, ins_info_key)
  File "/share/pkg.7/paragraph/2.4a/install/lib/python3/grm/vcfgraph/vcfgraph.py", line 202, in add_record
    self.add_alt(vcf.pos, vcf.stop, ref_sequence, alt_sequence, alt_samples, refSamples)
  File "/share/pkg.7/paragraph/2.4a/install/lib/python3/grm/vcfgraph/vcfgraph.py", line 296, in add_alt
    raise Exception("{}:{} missing REF or ALT sequence.".format(start, end))
Exception: 2893187:2893191 missing REF or ALT sequence.
"""
```

**Comment by traxexx** [comment]
For <INV>, Paragraph inverts REF sequences as ALT. Here, the REF sequence is C (padding base) + ATAT. After reverse complement, ATAT is still ATAT. There is a trimming step in graph building phase that eliminates same bases between REF and ALT. In this variant, all bases will be trimmed because they're the same...That's why you see this error message.

Actually this representation is confusing. It is a <INV> but it also has a INS sequence. @ctsa , what is the supposed ALT of this variant?

Thanks for reporting! v2.5 release will have a better error message on this situation.

**Comment by jjfarrell** [comment]
There is also a dup occurring at that site which may be complicating things:

```
chr6    2893187 MantaDUP:TANDEM:1:7410:7410:0:0:0;MantaDUP:TANDEM:8:21094:21094:1:0:0;MantaDUP:TANDEM:129143:0:0:0:0:0;MantaDUP:TANDEM:6:14973:14973:1:0:0;MantaDUP:TANDEM:98545:0:0:1:0:0;MantaDUP:TANDEM:62990:0:0:0:0:0;MantaDUP:TANDEM:66816:0:0:0:0:0;MantaDUP:TANDEM:2:21984:21984:1:0:0;MantaDUP:TANDEM:80362:0:0:0:0:0;MantaDUP:TANDEM:98083:0:0:0:0:0;MantaDUP:TANDEM:0:14436:14436:1:0:0;MantaDUP:TANDEM:7:10192:10192:0:0:0;MantaDUP:TANDEM:64160:0:0:0:0:0;MantaDUP:TANDEM:1:7753:7753:1:0:0;MantaDUP:TANDEM:4:10949:10949:1:0:0;MantaDUP:TANDEM:7:18966:18966:1:0:0;MantaDUP:TANDEM:7:12669:12669:1:0:0;MantaDUP:TANDEM:92715:0:0:1:0:0;MantaDUP:TANDEM:4:20498:20498:2:0:0;MantaDUP:TANDEM:75085:0:0:0:0:0;MantaDUP:TANDEM:0:13648:13648:1:0:0;MantaDUP:TANDEM:4:27357:27357:2:0:0;MantaDUP:TANDEM:75213:0:0:1:0:0;MantaDUP:TANDEM:0:5270:5270:1:0:0;MantaDUP:TANDEM:1:19103:19103:0:0:0;MantaDUP:TANDEM:2:15517:15517:1:0:0;MantaDUP:TANDEM:9:21216:21216:1:0:0;MantaDUP:TANDEM:5:13582:13582:1:0:0;MantaDUP:TANDEM:10:22557:22557:1:0:0;MantaDUP:TANDEM:0:13311:13311:1:0:0;MantaDUP:TANDEM:5:17416:17416:1:0:0;MantaDUP:TANDEM:63471:0:0:0:0:0;MantaDUP:TANDEM:5:21672:21672:1:0:0;MantaDUP:TANDEM:72641:0:0:0:0:0;MantaDUP:TANDEM:98874:0:0:1:0:0;MantaDUP:TANDEM:6:657:657:1:0:0;MantaDUP:TANDEM:64844:0:0:1:0:0;MantaDUP:TANDEM:69361:0:0:1:0:0;MantaDUP:TANDEM:8:18459:18459:1:0:0;MantaDUP:TANDEM:72455:0:0:0:0:0;MantaDUP:TANDEM:0:15177:15177:0:0:0;MantaDUP:TANDEM:82543:0:0:3:0:0;MantaDUP:TANDEM:100101:0:0:1:0:0;MantaDUP:TANDEM:3:34491:34491:2:0:0;MantaDUP:TANDEM:5:453:453:1:0:0;MantaDUP:TANDEM:71920:0:0:0:0:0;MantaDUP:TANDEM:75375:0:0:1:0:0;MantaDUP:TANDEM:8:22540:22540:1:0:0;MantaDUP:TANDEM:64714:0:0:0:0:0;MantaDUP:TANDEM:7:22858:22858:1:0:0;MantaDUP:TANDEM:68345:0:0:1:0:0;MantaDUP:TANDEM:64591:0:0:1:0:0;MantaDUP:TANDEM:7:9560:9560:1:0:0;MantaDUP:TANDEM:7:13563:13563:1:0:0;MantaDUP:TANDEM:64147:0:0:0:0:0;MantaDUP:TANDEM:71934:0:0:1:0:0;MantaDUP:TANDEM:2:15250:15250:1:0:0;MantaDUP:TANDEM:99981:0:0:1:0:0;MantaDUP:TANDEM:9:17467:17467:1:0:0;MantaDUP:TANDEM:0:22764:22764:1:0:0;MantaDUP:TANDEM:62283:0:0:0:0:0;MantaDUP:TANDEM:63120:0:0:2:0:0;MantaDUP:TANDEM:71271:0:0:1:0:0;MantaDUP:TANDEM:67500:0:0:1:0:0;MantaDUP:TANDEM:2:16398:16398:2:0:0;MantaDUP:TANDEM:6:13162:13162:0:0:0;MantaDUP:TANDEM:1:14161:14161:1:0:0;MantaDUP:TANDEM:3:24085:24085:1:0:0;MantaDUP:TANDEM:7:12967:12967:1:0:0;MantaDUP:TANDEM:0:9569:9569:2:0:0;MantaDUP:TANDEM:0:14270:14270:0:0:0;MantaDUP:TANDEM:7:17630:17630:0:0:0;MantaDUP:TANDEM:6:18095:18095:1:0:0;MantaDUP:TANDEM:6:23905:23905:1:0:0;MantaDUP:TANDEM:0:22231:22231:1:0:0;MantaDUP:TANDEM:0:486:486:0:0:0;MantaDUP:TANDEM:8:14872:14872:1:0:0;MantaDUP:TANDEM:65293:0:0:0:0:0;MantaDUP:TANDEM:2:22295:22295:0:0:0;MantaDUP:TANDEM:58519:0:0:0:0:0;MantaDUP:TANDEM:72661:0:0:1:0:0;MantaDUP:TANDEM:3:10030:10030:0:0:0;MantaDUP:TANDEM:12:23318:23318:0:0:0;MantaDUP:TANDEM:68906:0:0:0:0:0;MantaDUP:TANDEM:2:23725:23725:1:0:0;MantaDUP:TANDEM:0:15831:15831:0:0:0;MantaDUP:TANDEM:0:14511:14511:1:0:0;MantaDUP:TANDEM:72897:0:0:0:0:0;MantaDUP:TANDEM:74685:0:0:1:0:0;MantaDUP:TANDEM:77171:0:0:0:0:0;MantaDUP:TANDEM:59940:0:0:1:0:0;MantaDUP:TANDEM:3:8655:8655:0:0:0;MantaDUP:TANDEM:121919:0:0:1:0:0;MantaDUP:TANDEM:3:25904:25904:1:0:0;MantaDUP:TANDEM:182664:0:0:0:0:0;MantaDUP:TANDEM:175535:0:0:1:0:0;MantaDUP:TANDEM:62179:0:0:0:0:0;MantaDUP:TANDEM:8:16507:16507:1:0:0;MantaDUP:TANDEM:72402:0:0:0:0:0;MantaDUP:TANDEM:2:23155:23155:1:0:0;MantaDUP:TANDEM:1:14600:14600:1:0:0;MantaDUP:TANDEM:83098:0:0:2:0:0;MantaDUP:TANDEM:9:14467:14467:1:0:0;MantaDUP:TANDEM:80811:0:0:1:1:0;MantaDUP:TANDEM:86188:0:0:0:0:0;MantaDUP:TANDEM:10:22971:22971:0:0:0;MantaDUP:TANDEM:79300:0:0:1:0:0;MantaDUP:TANDEM:0:7401:7401:1:0:0;MantaDUP:TANDEM:45452:2:2:0:0:0;MantaDUP:TANDEM:3:15870:15870:1:0:0;MantaDUP:TANDEM:3:11374:11374:2:0:0;MantaDUP:TANDEM:72609:0:0:1:0:0;MantaDUP:TANDEM:137152:0:0:1:0:0;MantaDUP:TANDEM:0:9487:9487:1:0:0;MantaDUP:TANDEM:82080:0:0:2:0:0;MantaDUP:TANDEM:7:9696:9696:1:0:0;MantaDUP:TANDEM:3:14348:14348:1:0:0;MantaDUP:TANDEM:9:20435:20435:2:0:0;MantaDUP:TANDEM:2:24123:24123:1:0:0;MantaDUP:TANDEM:3:22140:22140:1:0:0;MantaDUP:TANDEM:0:16235:16235:1:0:0;MantaDUP:TANDEM:4:14045:14045:1:0:0;MantaDUP:TANDEM:10:15659:15659:1:0:0;MantaDUP:TANDEM:1:18638:18638:1:0:0;MantaDUP:TANDEM:3:16875:16875:1:0:0;MantaDUP:TANDEM:4:25043:25043:0:0:0;MantaDUP:TANDEM:0:9348:9348:1:0:0;MantaDUP:TANDEM:4:17754:17754:1:0:0;MantaDUP:TANDEM:70281:0:0:0:0:0;MantaDUP:TANDEM:163067:0:0:1:0:0;MantaDUP:TANDEM:100520:0:0:1:0:0;MantaDUP:TANDEM:70090:0:0:1:0:0;MantaDUP:TANDEM:159967:0:0:0:0:0;MantaDUP:TANDEM:5:12184:12184:0:0:0;MantaDUP:TANDEM:75650:0:0:1:0:0;MantaDUP:TANDEM:2:23861:23861:1:0:0;MantaDUP:TANDEM:69456:0:0:2:0:0;MantaDUP:TANDEM:23549:0:0:1:1:0;MantaDUP:TANDEM:68231:0:0:0:0:0;MantaDUP:TANDEM:72959:0:0:1:0:0;MantaDUP:TANDEM:72122:0:0:0:0:0;MantaDUP:TANDEM:61304:0:0:1:0:0;MantaDUP:TANDEM:55396:0:0:1:0:0;MantaDUP:TANDEM:57607:0:0:0:0:0;MantaDUP:TANDEM:15:23890:23890:2:0:0;MantaDUP:TANDEM:65646:0:0:1:0:0;MantaDUP:TANDEM:73940:0:0:1:0:0;MantaDUP:TANDEM:64731:0:0:1:0:0;MantaDUP:TANDEM:59342:0:0:1:0:0;MantaDUP:TANDEM:63461:0:0:0:0:0;MantaDUP:TANDEM:60535:0:0:0:0:0;MantaDUP:TANDEM:63063:0:0:1:0:0;MantaDUP:TANDEM:63281:0:0:1:0:0;MantaDUP:TANDEM:61343:0:0:1:0:0;MantaDUP:TANDEM:61130:0:0:1:0:0;MantaDUP:TANDEM:59978:0:0:0:0:0;MantaDUP:TANDEM:10:34233:34233:2:0:0;MantaDUP:TANDEM:66151:0:0:1:0:0;MantaDUP:TANDEM:58924:0:0:0:0:0;MantaDUP:TANDEM:63717:0:0:2:0:0;MantaDUP:TANDEM:66734:0:0:0:0:0;MantaDUP:TANDEM:8:30345:30345:0:1:0;MantaDUP:TANDEM:63098:0:0:0:0:0;MantaDUP:TANDEM:61660:0:0:0:0:0;MantaDUP:TANDEM:8:28796:28796:0:0:0;MantaDUP:TANDEM:3:11653:11653:0:0:0;MantaDUP:TANDEM:63674:0:0:1:0:0;MantaDUP:TANDEM:65859:0:0:0:0:0;MantaDUP:TANDEM:67949:0:0:0:0:0;MantaDUP:TANDEM:59436:0:0:1:0:0;MantaDUP:TANDEM:65757:0:0:0:0:0;MantaDUP:TANDEM:63077:0:0:1:0:0;MantaDUP:TANDEM:63016:0:0:2:1:0;MantaDUP:TANDEM:60566:0:0:1:0:0;MantaDUP:TANDEM:67776:0:0:1:0:0;MantaDUP:TANDEM:63475:0:0:1:0:0;MantaDUP:TANDEM:7:21517:21517:1:0:0;MantaDUP:TANDEM:63181:0:0:1:0:0;MantaDUP:TANDEM:65564:0:0:1:0:0;MantaDUP:TANDEM:61845:0:0:0:0:0;MantaDUP:TANDEM:71188:0:0:0:0:0;MantaDUP:TANDEM:65551:0:0:1:0:0;MantaDUP:TANDEM:69657:0:0:1:0:0;MantaDUP:TANDEM:8:19230:19230:0:0:0;MantaDUP:TANDEM:55093:0:0:0:0:0;MantaDUP:TANDEM:64871:0:0:1:0:0;MantaDUP:TANDEM:0:4703:4703:1:0:0;MantaDUP:TANDEM:65280:0:0:0:0:0;MantaDUP:TANDEM:75149:0:0:1:0:0;MantaDUP:TANDEM:68448:0:0:1:0:0;MantaDUP:TANDEM:54878:0:0:0:0:0;MantaDUP:TANDEM:0:21068:21068:1:0:0;MantaDUP:TANDEM:69793:0:0:0:0:0;MantaDUP:TANDEM:71422:0:0:1:0:0;MantaDUP:TANDEM:5:18792:18792:1:0:0;MantaDUP:TANDEM:65960:0:0:1:0:0;MantaDUP:TANDEM:68768:0:0:1:0:0;MantaDUP:TANDEM:61647:0:0:1:0:0;MantaDUP:TANDEM:2:20092:20092:1:0:0;MantaDUP:TANDEM:58980:0:0:0:0:0;MantaDUP:TANDEM:62613:0:0:1:1:0;MantaDUP:TANDEM:61240:0:0:0:0:0;MantaDUP:TANDEM:59156:0:0:0:0:0;MantaDUP:TANDEM:6:21712:21712:1:0:0;MantaDUP:TANDEM:63856:0:0:0:0:0;MantaDUP:TANDEM:60431:0:0:0:0:0;MantaDUP:TANDEM:59602:0:0:1:0:0;MantaDUP:TANDEM:58669:0:0:1:0:0;MantaDUP:TANDEM:60393:0:0:1:0:0;MantaDUP:TANDEM:6:26846:26846:0:0:0;MantaDUP:TANDEM:2:4072:4072:1:0:0;MantaDUP:TANDEM:58768:0:0:1:0:0;MantaDUP:TANDEM:58525:0:0:0:0:0;MantaDUP:TANDEM:60602:0:0:1:0:0  C       <DUP:TANDEM>    999     PASS    END=2893231;SVTYPE=DUP;SVLEN=44;SVINSLEN=73;SVINSSEQ=ATTATATATACGTATATATATACGTATATATAATATATATATTATATATACGTATATATAATATATATATATT;AC=217;AN=9578;FIBC_P=-0.0433043;HWE_SLP_P=-42.1212;FIBC_I=-0.0433133;HWE_SLP_I=-42.1553;MAX_IF=0.759877;MIN_IF=0.748001;LLK0=-268836;BETA_IF=0.505578,0.0461633,0.0721978,0.0701312,0.0841303;ANN=<DUP:TANDEM>|intron_variant|MODIFIER|SERPINB9|ENSG00000170542|transcript|ENST00000380698.4|protein_coding|5/6|c.567+180_567+223dup||||||;NS=4789;AF=0.0226561;MAF=0.0226561;AC_Het=211;AC_Hom=6;AC_Hemi=0;HWE=0.736495;ExcHet=0.771593
chr6    2893187 MantaINV:4:20498:20498:4:0:0;MantaINV:61660:0:0:1:0:0   C       <INV>   548     PASS    END=2893191;SVTYPE=INV;SVLEN=4;CIPOS=0,4;CIEND=-4,0;HOMLEN=4;HOMSEQ=TATA;SVINSLEN=51;SVINSSEQ=ACGTATATATATACGTATATATAATATATATATTATATATACGTATATATA;INV5;AC=2;AN=9578;FIBC_P=-0.000417444;HWE_SLP_P=-0.195618;FIBC_I=-0.000417444;HWE_SLP_I=-0.195618;MAX_IF=0.749985;MIN_IF=0.749985;LLK0=-281075;BETA_IF=0.49997,-3.8073e-06,1.89345e-06,3.9655e-06,2.17351e-06;ANN=<INV>|intron_variant|MODIFIER|SERPINB9|ENSG00000170542|transcript|ENST00000380698.4|protein_coding|5/6|c.567+220_567+223inv||||||;NS=4789;AF=0.000208812;MAF=0.000208812;AC_Het=2;AC_Hom=0;AC_Hemi=0;HWE=1;ExcHet=0.999896
```

**Comment by traxexx** [comment]
Let me try to check with Chris internally. For now I recommend skipping such ambiguous records.

**Comment by KamilSJaron** [comment]
I got the same problem with the following entry

```
scaf000253	514459	MantaINV:5899:0:0:0:0:0	N	<INV>	34	SampleFT	END=514542;SVTYPE=INV;SVLEN=83;IMPRECISE;CIPOS=-351,352;CIEND=-355,356;INV5	GT:FT:GQ:PL:PR	1/1:MinGQ:9:86,12,0:0,4
```

That same problem: `Exception: 514459:514542 missing REF or ALT sequence.`

Funny enough, this is for sure a wrong call or misassembly because it's the same individual that was used to build the reference.

If I would understand better on what paragraph expect, I could ad appropriate adjustments in [the following script](https://github.com/Illumina/paragraph/issues/42#issuecomment-598693860) to get them the manta output to paragraph compatible vcf file

**Comment by traxexx** [comment]
Your error is exactly the same as above. For now I suggest not including such records before figuring out what Manta really means for them.

**Comment by KamilSJaron** [comment]
As discussed in the last post of #42, `SVINSSEQ` is part of variants that are breakpoints with insertions. I.e. nested variants; inversions with an insertion on aside.

My solution was to filter them out.
