### ISSUE TITLE
Compatibility of paragraph and Sniffles VCF

### ISSUE THREAD

**Issue by biozzq** [Illumina/paragraph#51]
Dear @traxexx 

I ran following command to genotype the candidate deletion variants. Here the P1_DEL.vcf was generated by `Sniffles`, however the program exited with "Exception: Different padding base for REF and ALT at 1:233140". Maybe I need to some other custom scripts to convert the VCF file to be compatible with the paragraph.

`multigrmpy.py -i P1_DEL.vcf -m manifest -o P1_DEL.genotype -r reference.fa`
```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
1       233140  .       TGTCCTGTGTCCGTGTCCCATGGTGTCCGTGTCTCAGTCTGTCCTGTGTCCGGTCCCGTGTCCGTGTCCCGTGTCCCACGTCCATGTCCCGTGTCCGTGTCTCATGTCCGGGTCCCGTGTCCGTGTCCCACGTCCATGTCCCGTGTCCGTGTCTCATGTCTGGGTCCTGTGTCCATGTCCCATGTCCATGTCCCGTGTCCGTGTCTCATGTCTGGGTCCTGTGTCCGTGTCCCATGTCCATGTCCCGTGTCCGTGTCTCATGTCCGCGTCCGTGTCCATGTCCATGTCCGTGTCCGTGTCTCATGTCCGGTCCTGTCCGGTCCCCTGTCCGTGTCCCGTGTCCGTGTCTCATGTCCGTGTCTCATGTCCGGGTCCGTTCCGTGTCCCTGTCCATGTCCCGTGTCCGTGTCTCATGTCTGGGTCCTGTGTCCGTGTCCCGTCCATGTCCCGTGTCCGTGTCCTGTCCGGTCCTGTCCGTGTCCGTGTCCATGTCCCGTGTCCGTGTCCGTGTCCATGTCCCGTGTCCGTGTCTCATGTCCCG   N       0       .       PRECISE;SVMETHOD=Snifflesv1.0.11;CHR2=1;END=233681;ZMW=21;STD_quant_start=0;STD_quant_stop=0;Kurtosis_quant_start=7;Kurtosis_quant_stop=2.0032;SVTYPE=DEL;SUPTYPE=AL;SVLEN=-541;STRANDS=+-;STRANDS2=9,12,9,12;RE=21;REF_strand=13,14;AF=0.4375;MERGED_IDS=1,svim.DEL.5;NUM_JOINED_SVS=2;STDDEV_POS=0,2
1       233793  .       CACGTCCATGTCCCGTGTCCGTGTCTCATGTCCGGGTCCTGTGTCCGGTCCGTGTCCCGTGTCCGTGTCCCACGTCCATGTCCCGTGTCCGTGTCTCATGTCCGGTCCCGTGTCCGTGTCCCACGTCCATGTCCCGTGTCCGTGTCTCATGTCTCCGTGTCCTGTGTCCATGTCCGGTCCG   N       0       .       PRECISE;SVMETHOD=Snifflesv1.0.11;CHR2=1;END=233868;ZMW=26;STD_quant_start=0;STD_quant_stop=0;Kurtosis_quant_start=10;Kurtosis_quant_stop=10;SVTYPE=DEL;SUPTYPE=AL;SVLEN=-75;STRANDS=+-;STRANDS2=13,13,13,13;RE=26;REF_strand=0,0;AF=1;MERGED_IDS=2,svim.DEL.7;NUM_JOINED_SVS=2;STDDEV_POS=0,0
```
sincerely,
Zheng Zhuqing

**Comment by eberle** [comment]
Hello Zheng,

Thanks for using Paragraph and it looks like the vcf is incorrectly formatted. Usually, deletions are formatted like "REF = AT ; ALT = A" where A is the padding base and this indicates a deletion of the following T. Your vcf is formatted like "REF = AT ; ALT = N" and so the padding bases are different. I think that the solution is to either change the ALT to '.' or add on a padding base from position 233139. The second entry is going to have the same problem. 

Cheers,

-Mike

**Comment by biozzq** [comment]
Dear @eberle 

Thank you, It's OK now according to your suggestion. Also, it's same for the other types of SVs. I need to adjust the VCF (i.e., only 8 columns) to contain the following information presented in the README. 
```
<DEL> for deletion
Must have END key in INFO field.
<INS> for insertion
Must have a key in INFO field for insertion sequence (without padding base). The default key is SEQ.
For blockwise swap, we strongly recommend using indel-style representation, other than symbolic alleles.
<DUP> for duplication
Must have END key in INFO field. paraGRAPH assumes the sequence between POS and END being duplicated for one more time in the alternative allele.
<INV> for inversion
Must have END key in INFO field. paraGRAPH assumes the sequence between POS and END being reverse-complemented in the alternative allele.
```
Sincerely,
Zheng Zhuqing

**Comment by biozzq** [comment]
Dear @eberle 

I have tried to change the format according to your suggestion, however, the problem remains in the following variant.
```
1       438622  .       GTGGTGGTGATTGTGGTGGTGATGGTGGTGGTGATTGTGGTGGTGGTGGTGATGGTGGTGATGGTGATGGTGGTGGTGGTGGTGATGATGGTGATGGTGGTGGTGGTGGTGGTGATGGTGGTGGTGGTGGTGGTGGTGGTGGTGGGTGGTGGTGGTTGATGGTGATGGTGGTGGTGGTGGTGGTGTTGATGGTGATGGTGGTGGTGGTGGTGGTGGTGATGGTGATGGTGGTGGTGGTGGTGGTGATGGTGGTGGTGGTGGTGGTGGTGATGGTGGTGGTGGTGGTGATGGTGGTGGTGATGGTGGTGGTGGGTGTGGTGGTGGTGATGGTGGTGGTGGTGGTGGTGATGATTGTGGTGGAGATGGTGGTGGTGGTGGTGGTGGTTGCGGTAATGGTGGTGGTGGTGGTGGCGGTGATGGTGGTGGTGGTGGTGGCGGTGATGGTGGTGGTGGTGGTGATGGTGGTGGTGATGGTGGTTGTGGGTGTGGTGGTGGTGGTGGTGATGGTTGTGGGTGTGGTGGTGGTGATTGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGTTGATGGTGATGGTGGTGGTGGTGGTGGTGGTGATGGTGGTGATGGTGATGGTGGTGGTGGTGGTGATGATGGTGGTGGTGGTGGTGATGGTGGTGGTGATGGTGGTGGTGGGTGTGGTGGTGGTGATGGTGGTGGTGGTGGGTGTGGTGGTGGTGATGGTGGTGGTGGTGGTGGTGGTGGTGATGGTGGTGGTGATGGTGGTGGTGGTGGTGGTGATGGTGATGGTGGTGGTGGTGGTGGTGATGGTGGTGGTGGTGGTGGTGATGATGGTGGTGGTGGTGGTGATGGTGGTGGTGATGGTGGTGGTGGGTGTGGTGGTGGTGATGGTGGTGGTGGTGGTGGTGATGATTGTGGTGGTGATGGTGGTGGTGGTGGTGGTGGTGGCGGTGATGGTGGTGGTGGTGGTGATGGTGGTGGTGATGGTGGTTGTGGGTGTGGTGGTGGTGGTGGTGATGGTTGTGGGGTGTGGTGGTGGTGTTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGGTTGGTGGTGATGGTGGTGGTGGTGGTGGTGGTGATTGGTGGTGGTGGTGGTGATGGTGGTGTGGTGATGGTGGTGGTGGTGGTGTGTGGTGGTGGTGGTGGTGATGGTGGTGGTGTGGTGGTGGTGGGTGTGGTGGTGGTGATGGTGGTGGTGGTGGTGTGATTGTGGTGGTGATGGTGGTGGTGGTGGTGGTGGTGGCGGTGATGGTGGTGGTGGTGGTGGGGTGATGGTGGTGGTGGTGGTGATGGTGGTGGTGATGGTGGTTGGGGTGTGGTGGTGGTGGTGGTGATGGTTGTGGGTGTGGTGGTGGTGATTGTGGTGGTGGTGGTGGTGGTGGTGGTGATTGTGGTGGTGGTGGTGGTGATGGTGATGGTGGTGGTGGTGGTGGTGATGATGGTGTTGGTGGTGGTGGTGGTGATGGTGGTCGTGGTGGTGATGGTGGTGGTGGTGGTGGTGGTGATTGTGGTGGTGGTGGTGGTGGTGGTGGCGGTGGGTGGTGGTGGCGATGGTGGCGGTGGCAGTGGAGGTGGTGGCGGTGGTGTCGGTGGCGGTGGTGGTGGTGGCGGTGGTGGTGGTGGTGATGGTGGTGGCGTGATGGTGGTGGTGATGGTGGTGTGGTGGTGATGGTGGTGGTGGTGGTGGTGGTGATTGTGGTGGTGGTGGTGGTGGTGGGGTGGCGGTGGTGGTGGGGCGTGGTGGGGTGGAGTGGGGTGGTGGCGGTGGTGTGGTGGCGGTGGTGGGGTGGGGTGGTGGTGGTGGTGTGGTGGTGGGGTGGGTGGTGGGGGTGGGTGGTGGTGGTGGGGGGGTGGGTGGTGGTGGTGGGGTGGTGGTGTGGTGGTGGGTGGTGGTGGTGGGGTGGGGTGGTGTGGGGTGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGATGGTGGTGTGGTGGTCGTGGTGATGCTGGCAGTAATGATGGTGGTGGTGGTGGTGGTGCTGGTGGTGATGGTGCTGGTGGTGGTGGTGGTGGTGGTGATGGTGGTGATGGTGGTGGCAGTAAAGGTGGTGGTGGTGGCGGTGGTGGCGGTGGGGTGGCGA  G       0       .       PRECISE;SVMETHOD=Snifflesv1.0.11;CHR2=1;END=440811;ZMW=29;STD_quant_start=1.79284;STD_quant_stop=0;Kurtosis_quant_start=-1.20666;Kurtosis_quant_stop=4.10287;SVTYPE=DEL;SUPTYPE=AL,SR;SVLEN=-2189;STRANDS=+-;STRANDS2=16,13,16,13;RE=29;REF_strand=0,1;AF=0.966667;MERGED_IDS=15,svim.DEL.29;NUM_JOINED_SVS=2;STDDEV_POS=9,7
```
The error information,
```
2020-07-23 09:07:00,451 ERROR    TypeError: values expected to be 1-tuple, given len=2
2020-07-23 09:07:00,451 ERROR    During handling of the above exception, another exception occurred:
2020-07-23 09:07:00,451 ERROR    Traceback (most recent call last):
2020-07-23 09:07:00,451 ERROR      File "/stor9000/apps/users/NWSUAF/2015060145/ZhengZhuQing/00.script/paragraph/bin/multigrmpy.py", line 340, in run    vcfupdate.update_vcf_from_grmpy(vcf_input_path, grmpyOutput, result_vcf_path, sample_names)
2020-07-23 09:07:00,451 ERROR      File "/stor9000/apps/users/NWSUAF/2015060145/ZhengZhuQing/00.script/paragraph/lib/python3/grm/vcfgraph/vcfupdate.py", line 164, in update_vcf_from_grmpy    raise Exception("Format error in vcf line: " + str(raw_record))
2020-07-23 09:07:00,451 ERROR    Exception: Format error in vcf line: 1 438622  .       GTGGTGGTGATTGTGGTGGTGATGGTGGTGGTGATTGTGGTGGTGGTGGTGATGGTGGTGATGGTGATGGTGGTGGTGGTGGTGATGATGGTGATGGTGGTGGTGGTGGTGGTGATGGTGGTGGTGGTGGTGGTGGTGGTGGTGGGTGGTGGTGGTTGATGGTGATGGTGGTGGTGGTGGTGGTGTTGATGGTGATGGTGGTGGTGGTGGTGGTGGTGATGGTGATGGTGGTGGTGGTGGTGGTGATGGTGGTGGTGGTGGTGGTGGTGATGGTGGTGGTGGTGGTGATGGTGGTGGTGATGGTGGTGGTGGGTGTGGTGGTGGTGATGGTGGTGGTGGTGGTGGTGATGATTGTGGTGGAGATGGTGGTGGTGGTGGTGGTGGTTGCGGTAATGGTGGTGGTGGTGGTGGCGGTGATGGTGGTGGTGGTGGTGGCGGTGATGGTGGTGGTGGTGGTGATGGTGGTGGTGATGGTGGTTGTGGGTGTGGTGGTGGTGGTGGTGATGGTTGTGGGTGTGGTGGTGGTGATTGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGTTGATGGTGATGGTGGTGGTGGTGGTGGTGGTGATGGTGGTGATGGTGATGGTGGTGGTGGTGGTGATGATGGTGGTGGTGGTGGTGATGGTGGTGGTGATGGTGGTGGTGGGTGTGGTGGTGGTGATGGTGGTGGTGGTGGGTGTGGTGGTGGTGATGGTGGTGGTGGTGGTGGTGGTGGTGATGGTGGTGGTGATGGTGGTGGTGGTGGTGGTGATGGTGATGGTGGTGGTGGTGGTGGTGATGGTGGTGGTGGTGGTGGTGATGATGGTGGTGGTGGTGGTGATGGTGGTGGTGATGGTGGTGGTGGGTGTGGTGGTGGTGATGGTGGTGGTGGTGGTGGTGATGATTGTGGTGGTGATGGTGGTGGTGGTGGTGGTGGTGGCGGTGATGGTGGTGGTGGTGGTGATGGTGGTGGTGATGGTGGTTGTGGGTGTGGTGGTGGTGGTGGTGATGGTTGTGGGGTGTGGTGGTGGTGTTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGGTTGGTGGTGATGGTGGTGGTGGTGGTGGTGGTGATTGGTGGTGGTGGTGGTGATGGTGGTGTGGTGATGGTGGTGGTGGTGGTGTGTGGTGGTGGTGGTGGTGATGGTGGTGGTGTGGTGGTGGTGGGTGTGGTGGTGGTGATGGTGGTGGTGGTGGTGTGATTGTGGTGGTGATGGTGGTGGTGGTGGTGGTGGTGGCGGTGATGGTGGTGGTGGTGGTGGGGTGATGGTGGTGGTGGTGGTGATGGTGGTGGTGATGGTGGTTGGGGTGTGGTGGTGGTGGTGGTGATGGTTGTGGGTGTGGTGGTGGTGATTGTGGTGGTGGTGGTGGTGGTGGTGGTGATTGTGGTGGTGGTGGTGGTGATGGTGATGGTGGTGGTGGTGGTGGTGATGATGGTGTTGGTGGTGGTGGTGGTGATGGTGGTCGTGGTGGTGATGGTGGTGGTGGTGGTGGTGGTGATTGTGGTGGTGGTGGTGGTGGTGGTGGCGGTGGGTGGTGGTGGCGATGGTGGCGGTGGCAGTGGAGGTGGTGGCGGTGGTGTCGGTGGCGGTGGTGGTGGTGGCGGTGGTGGTGGTGGTGATGGTGGTGGCGTGATGGTGGTGGTGATGGTGGTGTGGTGGTGATGGTGGTGGTGGTGGTGGTGGTGATTGTGGTGGTGGTGGTGGTGGTGGGGTGGCGGTGGTGGTGGGGCGTGGTGGGGTGGAGTGGGGTGGTGGCGGTGGTGTGGTGGCGGTGGTGGGGTGGGGTGGTGGTGGTGGTGTGGTGGTGGGGTGGGTGGTGGGGGTGGGTGGTGGTGGTGGGGGGGTGGGTGGTGGTGGTGGGGTGGTGGTGTGGTGGTGGGTGGTGGTGGTGGGGTGGGGTGGTGTGGGGTGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGATGGTGGTGTGGTGGTCGTGGTGATGCTGGCAGTAATGATGGTGGTGGTGGTGGTGGTGCTGGTGGTGATGGTGCTGGTGGTGGTGGTGGTGGTGGTGATGGTGGTGATGGTGGTGGCAGTAAAGGTGGTGGTGGTGGCGGTGGTGGCGGTGGGGTGGCGA  G       0       .       PRECISE;SVMETHOD=Snifflesv1.0.11;CHR2=1;ZMW=29;STD_quant_start=1.7
9284;STD_quant_stop=0;Kurtosis_quant_start=-1.20666;Kurtosis_quant_stop=4.10287;SVTYPE=DEL;SUPTYPE=AL,SR;SVLEN=-2189;STRANDS=+-;STRANDS2=16,13,16,13;RE=29;REF_strand=0,1;AF=0.966667;MERGED_IDS=15,svim.DEL.29;NUM_JOINED_SVS=2;STDDEV_POS=9,7;GRMPY_ID=P1.vcf@549c911f4606c3e0c9d1bf7c66810785d49c7382a8fc7fa78bb7fb4e406df5b3:11
```

Sincerely,
Zheng Zhuqing

**Comment by traxexx** [comment]
This looks like a header issue from Sniffles. Here `TypeError: values expected to be 1-tuple, given len=2`
It's an htslib error.  An INFO field is expected to be tuple (from reading vcf records), but in the header it is represented as some other types. That could be the SUPTYPE field. Please check your vcf header. If this field is marked as string, change it to dot.
