### ISSUE TITLE
Pysam error message after paragraph genotyping completes

### ISSUE THREAD

**Issue by mchowdh200** [Illumina/paragraph#57]
Hi all,

I've been running into what I believe is a pysam error message when running multigrmpy.py.  Before I go into too much detail, here is some background info on what I'm trying to do.

I've been working on an experiment where I take a mixture of two separate BAMS which have been sampled using `samtools view -s` and mixed with `samtools merge`.  Then I try to genotype some variants from one of the two samples to see how robust Paragraph is to varying allele balance (by varying the mixture ratios of the two sample bams).

Paragraph seems to run just fine on a mixture BAM, since it seems to output and populate the genotypes.json.gz.  In grmpy.log, the log messages do not indicate any errors and it seems to get through the entire genotyping process.  It seems that when the time comes to create the corresponding genotypes.vcf.gz, I get a pysam error.

`2020-11-03 06:18:01,921 ERROR    Traceback (most recent call last):
2020-11-03 06:18:01,921 ERROR      File "/mnt/local/paragraph/build/bin/multigrmpy.py", line 340, in run    vcfupdate.update_vcf_from_grmpy(vcf_input_path, grmpyOutput, result_vcf_path, sample_names)
2020-11-03 06:18:01,921 ERROR      File "/mnt/local/paragraph/build/lib/python3/grm/vcfgraph/vcfupdate.py", line 232, in update_vcf_from_grmpy    set_record_for_sample(record, sample, grmpyRecord, alleleMap)
2020-11-03 06:18:01,921 ERROR      File "/mnt/local/paragraph/build/lib/python3/grm/vcfgraph/vcfupdate.py", line 310, in set_record_for_sample    record.samples[sample]["PL"] = pls_to_set
2020-11-03 06:18:01,921 ERROR      File "pysam/libcbcf.pyx", line 3455, in pysam.libcbcf.VariantRecordSample.__setitem__
2020-11-03 06:18:01,921 ERROR      File "pysam/libcbcf.pyx", line 859, in pysam.libcbcf.bcf_format_set_value
2020-11-03 06:18:01,921 ERROR      File "pysam/libcbcf.pyx", line 597, in genexpr
2020-11-03 06:18:01,921 ERROR      File "pysam/libcbcf.pyx", line 597, in genexpr
2020-11-03 06:18:01,921 ERROR      File "pysam/libcutils.pyx", line 129, in pysam.libcutils.force_bytes
2020-11-03 06:18:01,921 ERROR    TypeError: Argument must be string, bytes or unicode.
Traceback (most recent call last):
  File "/mnt/local/paragraph/build/bin/multigrmpy.py", line 353, in <module>
    main()
  File "/mnt/local/paragraph/build/bin/multigrmpy.py", line 349, in main
    run(args)
  File "/mnt/local/paragraph/build/bin/multigrmpy.py", line 340, in run
    vcfupdate.update_vcf_from_grmpy(vcf_input_path, grmpyOutput, result_vcf_path, sample_names)
  File "/mnt/local/paragraph/build/lib/python3/grm/vcfgraph/vcfupdate.py", line 232, in update_vcf_from_grmpy
    set_record_for_sample(record, sample, grmpyRecord, alleleMap)
  File "/mnt/local/paragraph/build/lib/python3/grm/vcfgraph/vcfupdate.py", line 310, in set_record_for_sample
    record.samples[sample]["PL"] = pls_to_set
  File "pysam/libcbcf.pyx", line 3455, in pysam.libcbcf.VariantRecordSample.__setitem__
  File "pysam/libcbcf.pyx", line 859, in pysam.libcbcf.bcf_format_set_value
  File "pysam/libcbcf.pyx", line 597, in genexpr
  File "pysam/libcbcf.pyx", line 597, in genexpr
  File "pysam/libcutils.pyx", line 129, in pysam.libcutils.force_bytes
TypeError: Argument must be string, bytes or unicode.`

My initial thought was that there could have been something wrong with the input vcf format, but I'm not sure where to start based on the error alone.

Thanks for your help, and please let me know if you need more details to clear  anything up.

**Comment by traxexx** [comment]
Yes if there is no errors in grmpy.log, the genotyping process should be ok. This looks like a VCF error. You can even tell where exactly the error is in pysam:
https://github.com/pysam-developers/pysam/blob/master/pysam/libcutils.pyx

When I need to figure out a pysam vcf error, I usually load the vcf into pysam and reprint everything out. That may tell you which line/field the error happens. Please let me know if this works for you.

**Comment by malemay** [comment]
I have had a similar problem, although for different reasons (one of the INFO fields was not appropriately specified in the header).

I understand that it is not the responsibility of the developers of Paragraph to fix the problems due to input vcf files, but it would be helpful if at least Paragraph could check for proper vcf input before genotyping so that it can fail early instead of after several hours of computing.

I also understand that it is possible to fix the vcf and then convert the json output to vcf without re-running the genotyping, but it would still be helpful and result in cleaner analyses if multigrmpy.py could fail early instead.
