### ISSUE TITLE
Exception: Different padding base for REF and ALT

### ISSUE THREAD

**Issue by srbehera** [Illumina/paragraph#61]
I am running paragraph for GIAB dataset and I used the following command 

`python3 .../bin/multigrmpy.py -i HG002_SVs_Tier1_v0.6_chr22.vcf -m samples.txt -r hg19.chr22.fa -o test `

My samples.txt file looks like the following 

i```
d	path	depth	read length
sample1	/stornext/snfs5/next-gen/scratch/fritz/projects/Sairam/Proj1_nibSV/TEST/HG002.hg19.chr22.bam	60	250
```

It throws the following error

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".../bin/multigrmpy.py", line 353, in <module>
    main()
  File ".../bin/multigrmpy.py", line 349, in main
    run(args)
  File ".../bin/multigrmpy.py", line 261, in run
    graph_files = load_graph_description(args)
  File ".../bin/multigrmpy.py", line 52, in load_graph_description
    header, records, event_list = convert_vcf_to_json(args, alt_paths=True)
  File ".../lib/python3/grm/vcf2paragraph/__init__.py", line 156, in convert_vcf_to_json
    variants = pool.map(run_vcf2paragraph, zip(to_process, itertools.repeat(params)))
  File ".../lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File ".../lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
Exception: Different padding base for REF and ALT at 22:18588640
```

**Comment by traxexx** [comment]
Could you please check if the padding is the same for REF and ALT at your VCF position 22:18588640?

**Comment by atongsa** [comment]
how to solve it if REF and ALT  have different padding sequece

**Comment by atongsa** [comment]
## ERROR    
```Exception: Different padding base for REF and ALT at NC_030811.1:2998385```

## vcf
```
NC_030811.1     2998385 MantaDEL:28854:0:0:0:0:0        CTGTGT        C
```

##

**Comment by dongling-hub** [comment]
Have you been able to resolve the issue mentioned previously? If so, what was the root cause of the problem?

**Comment by netwon123** [comment]
Could u solve this probleam?

**Comment by netwon123** [comment]
> ## ERROR
> `Exception: Different padding base for REF and ALT at NC_030811.1:2998385`
> 
> ## vcf
> ```
> NC_030811.1     2998385 MantaDEL:28854:0:0:0:0:0        CTGTGT        C
> ```
> 
> ## note
> i think this is the same padding seq both are C; how to solve this

hey! could u tell me the reason?
