### ISSUE TITLE
subprocess.CalledProcessError

### ISSUE THREAD

**Issue by duzezhen** [Illumina/paragraph#67]
I am using multigrmpy.py for genotyping. But the software keeps reporting errors, and I can't find the reason from the log. Can you help me see what might be the problem?

```
[W::vcf_parse] INFO 'ChrB' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO 'StartB' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO 'EndB' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO 'Parent' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO 'VarType' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO 'DupType' is not defined in the header, assuming Type=String
2021-10-10 22:49:51,956 ERROR    Traceback (most recent call last):
2021-10-10 22:49:52,013 ERROR      File "/public/home/software/opt/bio/software/Paragrpah/2.4a//bin/multigrmpy.py", line 315, in run    subprocess.check_call(commandline, shell=True, stderr=subprocess.STDOUT)
2021-10-10 22:49:52,013 ERROR      File "/public/home/software/opt/bio/software/Python/3.6.5/lib/python3.6/subprocess.py", line 291, in check_call    raise CalledProcessError(retcode, cmd)
2021-10-10 22:49:52,013 ERROR    subprocess.CalledProcessError: Command '/public/home/software/opt/bio/software/Paragrpah/2.4a/bin/grmpy --response-file=/tmp/paragraph_S2XEz/tmp7xssapc_.txt' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/public/home/software/opt/bio/software/Paragrpah/2.4a//bin/multigrmpy.py", line 353, in <module>
    main()
  File "/public/home/software/opt/bio/software/Paragrpah/2.4a//bin/multigrmpy.py", line 349, in main
    run(args)
  File "/public/home/software/opt/bio/software/Paragrpah/2.4a//bin/multigrmpy.py", line 315, in run
    subprocess.check_call(commandline, shell=True, stderr=subprocess.STDOUT)
  File "/public/home/software/opt/bio/software/Python/3.6.5/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/public/home/software/opt/bio/software/Paragrpah/2.4a/bin/grmpy --response-file=/tmp/paragraph_S2XEz/tmp7xssapc_.txt' returned non-zero exit status 1.
```

grmpy.log
`
[2021-10-10 22:49:51.274] [Genotyping] [265809] [critical] Starting alignment for sample f5 (1/5)
[2021-10-10 22:49:51.855] [Genotyping] [265809] [critical] ERROR: This thread caught an exception first
[2021-10-10 22:49:51.855] [Genotyping] [265809] [warning] WARNING: rethrowing a thread exception
[2021-10-10 22:49:51.914] [Genotyping] [265809] [critical] stoll
`

**Comment by srbehera** [comment]
Hi, I am just wondering how did you fix this error? I am also getting a similar error

```
subprocess.CalledProcessError: Command '/bin/grmpy --response-file=/space1/tmp/3230583.sug-moab/tmp3sjysw5o.txt' died with <Signals.SIGILL: 4>.
Command exited with non-zero status 1
```

**Comment by duzezhen** [comment]
Hi, sorry to reply you so late. The reason for my error is because the chromosome name contains ‘-’ (chr1-1). In another case, the paragraph requires that the starting position of the variant off-chromosome be at least one read. For example, if you have a variant ‘chr1 20 310’, but the read length is 100bp, then this variant must be deleted. I hope this letter could be helpful to you.
