### ISSUE TITLE
Problem starting the script multigrmpy.py

### ISSUE THREAD

**Issue by aaaniich** [Illumina/paragraph#77]
Hi!
I try to use this tool, but when I use this command:
**python3 bin/multigrmpy.py -i vvv.vcf  -m manchr3.txt -r genome.fa -o test4**

I have next errors:

**in manifestrse the options: Unknown column read length
2023-01-19 10:05:07,167 ERROR    Traceback (most recent call last):
2023-01-19 10:05:07,167 ERROR      File "bin/multigrmpy.py", line 316, in run    subprocess.check_call(commandline, shell=True, stderr=subprocess.STDOUT)
2023-01-19 10:05:07,167 ERROR      File "/usr/lib/python3.6/subprocess.py", line 311, in check_call    raise CalledProcessError(retcode, cmd)
2023-01-19 10:05:07,167 ERROR    subprocess.CalledProcessError: Command '/opt/paragraph-build/bin/grmpy --response-file=/tmp/tmpmavc_bwf.txt' returned non-zero exit status 1.**

Can youexplain me, what's wrong?

**Comment by mzwaig** [comment]
I'm getting a similar error

**Comment by Han-Cao** [comment]
I also ran into this error and found it is caused by Windows line endings. You can check the manifest file and replace all '\r\n' with '\n'
