### ISSUE TITLE
Distance between vcf position and chrom start is smaller than read length.

### ISSUE THREAD

**Issue by pingxinxing** [Illumina/paragraph#83]
2024-06-22 10:50:05,945 ERROR    VCF to JSON conversion failed.
2024-06-22 10:50:05,946 ERROR    Traceback (most recent call last):
2024-06-22 10:50:05,946 ERROR      File "/home/Dongxianggui/anaconda3/envs/paragraph2/bin/multigrmpy.py", line 52, in load_graph_description    header, records, event_list = convert_vcf_to_json(args, alt_paths=True)
2024-06-22 10:50:05,946 ERROR      File "/home/Dongxianggui/anaconda3/envs/paragraph2/lib/python3/grm/vcf2paragraph/__init__.py", line 133, in convert_vcf_to_json    header, records, block_ids = parse_vcf_lines(args.input, args.read_length, args.split_type)
2024-06-22 10:50:05,946 ERROR      File "/home/Dongxianggui/anaconda3/envs/paragraph2/lib/python3/grm/vcf2paragraph/__init__.py", line 209, in parse_vcf_lines    raise Exception("Distance between vcf position and chrom start is smaller than read length.")
2024-06-22 10:50:05,946 ERROR    Exception: Distance between vcf position and chrom start is smaller than read length.
2024-06-22 10:50:05,946 ERROR    Traceback (most recent call last):
2024-06-22 10:50:05,946 ERROR      File "/home/Dongxianggui/anaconda3/envs/paragraph2/bin/multigrmpy.py", line 261, in run    graph_files = load_graph_description(args)
2024-06-22 10:50:05,946 ERROR      File "/home/Dongxianggui/anaconda3/envs/paragraph2/bin/multigrmpy.py", line 52, in load_graph_description    header, records, event_list = convert_vcf_to_json(args, alt_paths=True)
2024-06-22 10:50:05,946 ERROR      File "/home/Dongxianggui/anaconda3/envs/paragraph2/lib/python3/grm/vcf2paragraph/__init__.py", line 133, in convert_vcf_to_json    header, records, block_ids = parse_vcf_lines(args.input, args.read_length, args.split_type)
2024-06-22 10:50:05,946 ERROR      File "/home/Dongxianggui/anaconda3/envs/paragraph2/lib/python3/grm/vcf2paragraph/__init__.py", line 209, in parse_vcf_lines    raise Exception("Distance between vcf position and chrom start is smaller than read length.")
2024-06-22 10:50:05,946 ERROR    Exception: Distance between vcf position and chrom start is smaller than read length.
Traceback (most recent call last):
  File "/home/Dongxianggui/anaconda3/envs/paragraph2/bin/multigrmpy.py", line 353, in <module>
    main()
  File "/home/Dongxianggui/anaconda3/envs/paragraph2/bin/multigrmpy.py", line 349, in main
    run(args)
  File "/home/Dongxianggui/anaconda3/envs/paragraph2/bin/multigrmpy.py", line 261, in run
    graph_files = load_graph_description(args)
  File "/home/Dongxianggui/anaconda3/envs/paragraph2/bin/multigrmpy.py", line 52, in load_graph_description
    header, records, event_list = convert_vcf_to_json(args, alt_paths=True)
  File "/home/Dongxianggui/anaconda3/envs/paragraph2/lib/python3/grm/vcf2paragraph/__init__.py", line 133, in convert_vcf_to_json
    header, records, block_ids = parse_vcf_lines(args.input, args.read_length, args.split_type)
  File "/home/Dongxianggui/anaconda3/envs/paragraph2/lib/python3/grm/vcf2paragraph/__init__.py", line 209, in parse_vcf_lines
    raise Exception("Distance between vcf position and chrom start is smaller than read length.")
Exception: Distance between vcf position and chrom start is smaller than read length.
Hello, author, I want to know how to solve this situation.

**Comment by ghost** [comment]
I wonder if you solved this problem,thanks,bro

**Comment by pingxinxing** [comment]
sorry,i not solved this problem
&nbsp;


平新新
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2025年1月24日(星期五) 晚上9:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Illumina/paragraph] Distance between vcf position and chrom start is smaller than read length. (Issue #83)














 
I wonder if you solved this problem,thanks,bro
